import 'package:ar_test/models/treasures.dart';

final List<Treasure> huntTreasures = [
  Treasure(
      id: '1',
      name: "Iroke Ifa Divination Tapper",
      description: "A tool used in Yoruba divination ceremonies.",
      region: "South West",
      type: "3D Artifact",
      imageUrl: "assets/images/iroke_ifa.png",
      modelUrl: "assets/iroke_ifa_divination_tapper.glb",
      historicalSignificance:
          "Before a babaláwo, or diviner, began the process of divination or Ifa, a tapper was used on the divination tray to call Orunmila, the god of wisdom responsible for divination. Usually made from wood or ivory, the tapper, called iroke ifa, was also used to add rhythm to the babaláwo's chants. The form of the tapper helped invoke Orunmila through the stance of the woman carved in the middle, whose kneeling position, ikunle, was a gesture of respect.",
      latitude: 7.3775,
      longitude: 3.9470,
      clue: "Seek out the ceremonial object that bridges the earthly and the spiritual in Yoruba culture."),
  Treasure(
      id: '2',
      name: "Chief Obafemi Awolowo",
      description:
          "A nationalist and statesman who played a significant role in Nigeria's struggle for independence and was a major political leader in the Western Region.",
      region: "South West",
      type: "Historical Person",
      imageUrl: "assets/obafemi awolowo.jpg",
      modelUrl: "assets/user_3d_icon.glb",
      historicalSignificance:
          "A key figure in the struggle for Nigeria's independence.",
      latitude: 7.1475,
      longitude: 3.3619,
      clue:
          "Find the visionary leader in the heart of Yoruba land."),
  Treasure(
      id: '3',
      name: "Nigerian Independence (1960)",
      description: "The year Nigeria gained independence from British rule.",
      region: "South West",
      type: "Historical Snaps",
      imageUrl: "assets/independence delcaration.jpg",
      modelUrl: "assets/stereoscopic_camera.glb",
      historicalSignificance: "A pivotal moment in Nigeria's history.",
      latitude: 6.5244,
      longitude: 3.3792,
      clue:
          "Discover the site where the declaration of independence was celebrated."),
  Treasure(
      id: '4',
      name: "Words by Chief Obafemi Awolowo",
      description:
          "\"Do not enjoy while in office what you cannot afford while out of office.\"",
      region: "South West",
      type: "Quote",
      imageUrl: "assets/images/quote_awolowo.png",
      modelUrl: "assets/scroll.glb",
      historicalSignificance:
          "",
      latitude: 7.1475,
      longitude: 3.3619,
      clue:
          "Find the words of wisdom from the great leader of the Yoruba people."),
  Treasure(
      id: '5',
      name: "Egungun Mask",
      description: "A traditional Yoruba masquerade mask.",
      region: "South West",
      type: "Artifact",
      imageUrl: "assets/egungun mask.jpg",
      modelUrl: "assets/stereoscopic_camera.glb",
      historicalSignificance: "This mask would have been worn during the annual or biannual Egungun festival, performances and celebrations to honor lineage ancestors. In addition to their deployment during the annual festivals, Egungun masks can also be brought out at funerals for important lineage members or in times of crisis, when the guidance of the ancestors is sought",
      latitude: 7.3775,
      longitude: 3.9470,
      clue: "Search for the mask that brings ancestral spirits to life."),
  Treasure(
      id: '6',
      name: "Benin Bronze Plaque",
      description: "The 'Benin Bronzes' (made of brass and bronze) are a group of sculptures which include elaborately decorated cast relief plaques, commemorative heads, animal and human figures, items of royal regalia, and personal ornaments. They were created from at least the 1500s onwards in the West African Kingdom of Benin, by a specialist guild working for the royal court of the Oba (king) in Benin City.",
      region: "South South",
      type: "3D Artifact",
      imageUrl: "assets/Benin-Bronze-Plaque.jpg",
      modelUrl: "assets/stereoscopic_camera.glb",
      historicalSignificance:
          "Represents the rich artistry of the Benin Kingdom.",
      latitude: 6.3350,
      longitude: 5.6037,
      clue: "Look for the intricate bronze artwork of the Benin Kingdom."),
  Treasure(
      id: '7',
      name: "Ken Saro-Wiwa",
      description: "An environmental activist and writer",
      region: "South South",
      type: "Historical Person",
      imageUrl: "assets/ken_saro_wiwa.jpg",
      modelUrl: "assets/user_3d_icon.glb",
      historicalSignificance:
          "Ken Saro-Wiwa was a prominent Nigerian writer, environmental activist, and leader of the Ogoni people who fought against the environmental degradation caused by oil extraction in the Niger Delta. Through his organization, the Movement for the Survival of the Ogoni People (MOSOP), Saro-Wiwa highlighted the ecological damage and human rights abuses inflicted by oil companies and the Nigerian government. His activism led to clashes with the authorities, culminating in his arrest and trial by a military regime. Despite widespread international protests, Saro-Wiwa was executed by hanging in 1995, along with eight other Ogoni activists, sparking global outrage and condemnation.",
      latitude: 4.5361,
      longitude: 7.0733,
      clue: "Find the statue of the renowned Ogoni freedom fighter"),
  Treasure(
      id: '8',
      name: "Niger Delta Crisis",
      description:
          "A series of conflicts and unrest in the Niger Delta region.",
      region: "South South",
      type: "Historical Event",
      imageUrl: "assets/niger_delta_crisis.jpg",
      modelUrl: "assets/stereoscopic_camera.glb",
      historicalSignificance: "The Niger Delta conflict is a prolonged struggle in Nigeria's oil-rich Niger Delta over environmental damage, economic exploitation, and local autonomy. Local communities have battled oil companies and government neglect, resulting in severe environmental degradation and human rights abuses. The conflict has led to militant activities, sabotage, and clashes with the military, causing ongoing violence, a humanitarian crisis, and economic instability in the region.",
      latitude: 4.7750,
      longitude: 6.9986,
      clue: "Discover the events that shaped the Niger Delta crisis."),
  Treasure(
      id: '9',
      name: "Word of Ken Saro-Wiwa",
      description:
          "\"I have no doubt at all about the ultimate success of my cause no matter the trials and tribulations which I and those who believe with me may encounter in the course of the struggle. We all stand before history.\"",
      region: "South South",
      type: "Quote",
      imageUrl: "assets/images/quote_jaja.png",
      modelUrl: "",
      historicalSignificance: "",
      latitude: 4.5361,
      longitude: 7.0733,
      clue: "Find the words of Ken Saro Wiwa before he was executed"),
  Treasure(
      id: '10',
      name: "Ijaw War Canoe",
      description: "A traditional war canoe used by the Ijaw people.",
      region: "South South",
      type: "Artifact",
      imageUrl: "assets/images/ijaw_canoe.png",
      modelUrl: "",
      historicalSignificance:
          "Represents the maritime prowess of the Ijaw people.",
      latitude: 4.8288,
      longitude: 6.9786,
      clue:
          "Search for the war canoe that symbolizes the strength of the Ijaw people."),
  Treasure(
      id: '11',
      name: "Igbo Ukwu Bronze",
      description: "Ancient bronze artifacts from the Igbo Ukwu civilization.",
      region: "South East",
      type: "3D Artifact",
      imageUrl: "assets/images/igbo_ukwu.png",
      modelUrl: "assets/models/igbo_ukwu_bronze.glb",
      historicalSignificance:
          "Remarkable artworks representing early Igbo civilization.",
      latitude: 6.5244,
      longitude: 7.4916,
      clue:
          "Discover the ancient bronze artifacts that tell the story of Igbo heritage."),
  Treasure(
      id: '12',
      name: "Nnamdi Azikiwe",
      description:
          "Nigeria's first President and a key figure in the independence movement.",
      region: "South East",
      type: "Historical Person",
      imageUrl: "assets/images/nnamdi_azikiwe.png",
      modelUrl: "",
      historicalSignificance:
          "A pivotal leader in Nigeria's fight for independence.",
      latitude: 6.4500,
      longitude: 7.5000,
      clue: "Find the statue of the first President of Nigeria."),
  Treasure(
      id: '13',
      name: "Aba Women's Riot (1929)",
      description: "A major protest led by women in colonial Nigeria.",
      region: "South East",
      type: "Historical Event",
      imageUrl: "assets/images/aba_womens_riot.png",
      modelUrl: "",
      historicalSignificance:
          "A significant event in the history of resistance against colonial rule.",
      latitude: 5.1066,
      longitude: 7.3667,
      clue: "Discover the site of the historic women's protest."),
  Treasure(
      id: '14',
      name: "Quote by Nnamdi Azikiwe",
      description:
          "\"It is better we disintegrate in peace and not in pieces.\"",
      region: "South East",
      type: "Quote",
      imageUrl: "assets/images/quote_azikiwe.png",
      modelUrl: "",
      historicalSignificance:
          "A reflection on Nigeria's unity and potential fragmentation.",
      latitude: 6.4500,
      longitude: 7.5000,
      clue: "Find the words of wisdom from Nigeria's first President."),
  Treasure(
      id: '15',
      name: "Ozo Chieftaincy Regalia",
      description: "Traditional regalia worn by Ozo titled men in Igboland.",
      region: "South East",
      type: "Artifact",
      imageUrl: "assets/images/ozo_regalia.png",
      modelUrl: "",
      historicalSignificance:
          "Symbolizes the status and authority of Ozo titled men.",
      latitude: 6.5244,
      longitude: 7.4916,
      clue: "Search for the regalia that marks the honor of Ozo chieftains."),
  Treasure(
      id: '16',
      name: "Nok Terracotta",
      description: "Ancient terracotta sculptures from the Nok culture.",
      region: "North Central",
      type: "3D Artifact",
      imageUrl: "assets/images/nok_terracotta.png",
      modelUrl: "assets/models/nok_terracotta.glb",
      historicalSignificance:
          "Early examples of African artistry, dating back to 500 BC.",
      latitude: 9.0579,
      longitude: 7.4951,
      clue: "Find the ancient terracotta sculptures of the Nok people."),
  Treasure(
      id: '17',
      name: "Sir Ahmadu Bello",
      description: "The Sardauna of Sokoto and Premier of Northern Nigeria.",
      region: "North Central",
      type: "Historical Person",
      imageUrl: "assets/images/ahmadu_bello.png",
      modelUrl: "",
      historicalSignificance:
          "A prominent leader and advocate for the Northern region.",
      latitude: 10.2152,
      longitude: 7.9585,
      clue: "Find the statue of the revered leader of Northern Nigeria."),
  Treasure(
      id: '18',
      name: "Jos Plateau Crisis",
      description: "A series of violent conflicts in the Jos region.",
      region: "North Central",
      type: "Historical Event",
      imageUrl: "assets/images/jos_crisis.png",
      modelUrl: "",
      historicalSignificance:
          "A significant period of ethnic and religious conflict.",
      latitude: 9.8965,
      longitude: 8.8583,
      clue: "Discover the events that shaped the history of Jos Plateau."),
  Treasure(
      id: '19',
      name: "Quote by Sir Ahmadu Bello",
      description:
          "\"Education is the most important weapon which you can use to change the world.\"",
      region: "North Central",
      type: "Quote",
      imageUrl: "assets/images/quote_bello.png",
      modelUrl: "",
      historicalSignificance:
          "A statement on the power of education in societal transformation.",
      latitude: 10.2152,
      longitude: 7.9585,
      clue: "Find the wise words of the Sardauna of Sokoto."),
  Treasure(
      id: '20',
      name: "Tiv Traditional Dance Costume",
      description: "Traditional attire worn during Tiv dances.",
      region: "North Central",
      type: "Artifact",
      imageUrl: "assets/images/tiv_dance_costume.png",
      modelUrl: "",
      historicalSignificance:
          "Represents the cultural heritage of the Tiv people.",
      latitude: 7.6808,
      longitude: 8.8531,
      clue: "Search for the colorful costume of the Tiv dancers."),
  Treasure(
      id: '21',
      name: "Durbar Festival",
      description:
          "A festival featuring horse parades and celebrations in Northern Nigeria.",
      region: "North West",
      type: "3D Event",
      imageUrl: "assets/images/durbar_festival.png",
      modelUrl: "assets/models/durbar_festival.glb",
      historicalSignificance:
          "A major cultural and social event in Northern Nigeria.",
      latitude: 12.0022,
      longitude: 8.5919,
      clue: "Look for the grand celebrations of the Durbar Festival."),
  Treasure(
      id: '22',
      name: "Usman dan Fodio",
      description:
          "The founder of the Sokoto Caliphate and leader of the Fulani Jihad.",
      region: "North West",
      type: "Historical Person",
      imageUrl: "assets/images/usman_dan_fodio.png",
      modelUrl: "",
      historicalSignificance:
          "A key figure in the spread of Islam in West Africa.",
      latitude: 13.0059,
      longitude: 5.2476,
      clue: "Find the statue of the revered Islamic scholar and leader."),
  Treasure(
      id: '23',
      name: "Hausa Fulani Conflict",
      description: "A historic conflict between the Hausa and Fulani people.",
      region: "North West",
      type: "Historical Event",
      imageUrl: "assets/images/hausa_fulani_conflict.png",
      modelUrl: "",
      historicalSignificance:
          "A significant conflict in the history of Northern Nigeria.",
      latitude: 11.5200,
      longitude: 3.8774,
      clue:
          "Discover the history of the conflict between the Hausa and Fulani."),
  Treasure(
      id: '24',
      name: "Quote by Usman dan Fodio",
      description: "\"Conscience is an open wound, only truth can heal it.\"",
      region: "North West",
      type: "Quote",
      imageUrl: "assets/images/quote_dan_fodio.png",
      modelUrl: "",
      historicalSignificance: "A profound statement on truth and conscience.",
      latitude: 13.0059,
      longitude: 5.2476,
      clue: "Find the wise words of the founder of the Sokoto Caliphate."),
  Treasure(
      id: '25',
      name: "Sokoto Caliphate Coins",
      description: "Coins from the Sokoto Caliphate era.",
      region: "North West",
      type: "Artifact",
      imageUrl: "assets/images/sokoto_coins.png",
      modelUrl: "",
      historicalSignificance:
          "Represents the economic history of the Sokoto Caliphate.",
      latitude: 13.0059,
      longitude: 5.2476,
      clue:
          "Search for the coins that circulated during the Sokoto Caliphate era."),
  Treasure(
      id: '26',
      name: "Kanuri Pottery",
      description: "Traditional pottery made by the Kanuri people.",
      region: "North East",
      type: "3D Artifact",
      imageUrl: "assets/images/kanuri_pottery.png",
      modelUrl: "assets/models/kanuri_pottery.glb",
      historicalSignificance:
          "Represents the artistry and craftsmanship of the Kanuri people.",
      latitude: 11.8333,
      longitude: 13.1500,
      clue: "Look for the traditional pottery of the Kanuri people."),
  Treasure(
      id: '27',
      name: "Shehu of Borno",
      description: "A title for the traditional ruler of the Borno Emirate.",
      region: "North East",
      type: "Historical Person",
      imageUrl: "assets/images/shehu_borno.png",
      modelUrl: "",
      historicalSignificance:
          "A significant figure in the history and leadership of Borno.",
      latitude: 11.8333,
      longitude: 13.1500,
      clue: "Find the statue of the Shehu of Borno."),
  Treasure(
      id: '28',
      name: "Maitatsine Uprising",
      description: "A series of religious riots led by the Maitatsine sect.",
      region: "North East",
      type: "Historical Event",
      imageUrl: "assets/images/maitatsine_uprising.png",
      modelUrl: "",
      historicalSignificance: "A major religious conflict in Northern Nigeria.",
      latitude: 11.8333,
      longitude: 13.1500,
      clue: "Discover the history of the Maitatsine uprising."),
  Treasure(
      id: '29',
      name: "Quote by Shehu of Borno",
      description:
          "\"The strength of a leader lies in his ability to unite his people.\"",
      region: "North East",
      type: "Quote",
      imageUrl: "assets/images/quote_shehu.png",
      modelUrl: "",
      historicalSignificance: "A statement on leadership and unity.",
      latitude: 11.8333,
      longitude: 13.1500,
      clue: "Find the wise words of the Shehu of Borno."),
  Treasure(
      id: '30',
      name: "Kanem-Bornu Empire Shield",
      description:
          "A traditional shield used by warriors of the Kanem-Bornu Empire.",
      region: "North East",
      type: "Artifact",
      imageUrl: "assets/images/kanem_bornu_shield.png",
      modelUrl: "",
      historicalSignificance:
          "Represents the military history of the Kanem-Bornu Empire.",
      latitude: 11.8333,
      longitude: 13.1500,
      clue:
          "Search for the shield that protected the warriors of the Kanem-Bornu Empire.")
];
