// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzgCTTEqhTw5Lruro5iruQWgNEnQQ6gAA',
    appId: '1:15817954716:web:ea325856709dccf1c8a459',
    messagingSenderId: '15817954716',
    projectId: 'heritage-quest',
    authDomain: 'heritage-quest.firebaseapp.com',
    storageBucket: 'heritage-quest.appspot.com',
    measurementId: 'G-GSQ8BNQ8D0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByc3Vg6GJGtxRMBYscT0lLJw3A7nllza8',
    appId: '1:15817954716:ios:871493b9091780f5c8a459',
    messagingSenderId: '15817954716',
    projectId: 'heritage-quest',
    storageBucket: 'heritage-quest.appspot.com',
    iosClientId: '15817954716-hnpelubqkm8ihboek465vchh7ld2o1js.apps.googleusercontent.com',
    iosBundleId: 'com.example.arTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzgCTTEqhTw5Lruro5iruQWgNEnQQ6gAA',
    appId: '1:15817954716:web:64d7a85053eb5b95c8a459',
    messagingSenderId: '15817954716',
    projectId: 'heritage-quest',
    authDomain: 'heritage-quest.firebaseapp.com',
    storageBucket: 'heritage-quest.appspot.com',
    measurementId: 'G-6JSV16GJ9N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByc3Vg6GJGtxRMBYscT0lLJw3A7nllza8',
    appId: '1:15817954716:ios:871493b9091780f5c8a459',
    messagingSenderId: '15817954716',
    projectId: 'heritage-quest',
    storageBucket: 'heritage-quest.appspot.com',
    iosClientId: '15817954716-hnpelubqkm8ihboek465vchh7ld2o1js.apps.googleusercontent.com',
    iosBundleId: 'com.example.arTest',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnWBPcTEiqH2OqsE00B0OVLAd6uMjZLM',
    appId: '1:15817954716:android:cb56c4f2b242a9bac8a459',
    messagingSenderId: '15817954716',
    projectId: 'heritage-quest',
    storageBucket: 'heritage-quest.appspot.com',
  );

}